# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import petsy.models


class Migration(migrations.Migration):

    dependencies = [
        ('petsy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='img_shop',
            field=models.ImageField(default='/default-shop-img.jpg', upload_to=petsy.models.get_image_filename_post),
        ),
    ]
